#!/usr/bin/env bash
set -e
echo "=== chatxz Android Build ==="
echo ""
echo "Option 1: PWA (Add to Home Screen)"
echo "  Open http://<server-ip>:8742 in Chrome on Android"
echo "  Tap menu → 'Add to Home Screen'"
echo "  This creates a standalone app icon that opens chatxz"
echo "  Requires the server running on your LAN (use --share flag)"
echo ""
echo "Option 2: WebView APK via Bubblewrap"
echo "  Requires: nodejs, npm, android-sdk, jdk"
echo ""
echo "  npm install -g @bubblewrap/cli"
echo "  bubblewrap init --manifest=http://<server-ip>:8742/static/manifest.json"
echo "  bubblewrap build"
echo "  # Outputs: app-release-signed.apk"
echo ""
echo "Option 3: Termux (run server on phone)"
echo "  Install Termux from F-Droid"
echo "  In Termux:"
echo "    pkg install python git"
echo "    pip install rns aiohttp"
echo "    git clone https://github.com/narl3yyy-svg/chatzx.git"
echo "    cd chatzx"
echo "    python -m chatxz.web.server --share --port 8742"
echo "  Then open http://localhost:8742 in browser"
echo "  Or use PWA 'Add to Home Screen' for app-like experience"
echo ""
echo "Option 4: Standalone APK with embedded Python (Chaquopy)"
echo "  Requires: Android Studio, Android SDK"
echo "  1. Create new Android project with WebView"
echo "  2. Add Chaquopy plugin to build.gradle"
echo "  3. Bundle Python + rns + aiohttp"
echo "  4. Start Python server in a service"
echo "  5. WebView points to http://localhost:8742"
echo "  See: https://chaquo.com/chaquopy/"
